#include "set.h"
using namespace std;
int main(){
    string add, rm;
    Set<string>s1, s2, s3;
    cin >> s1;
    cin >> s2;
    cout << "Set 1: " << s1;
    cout << "Set 2: " << s2;
    s3=s1+s2;
    cout << "Union: " << s3;
    s3=s1^s2;
    cout << "Intersection: " << s3;
    s3=s1-s2;
    cout << "Difference (Set 1 - Set 2) " << s3;
    cout << "Add one interger to Set 1: ";
    cin >> add;
    s3= s1+add;
    cout << "Set 1: " << s3;
    Set<int>i1, i2, i3;
    int addi, rmi;
    cin >> i1;
    cin >> i2;
    cout << "Set 1: " << i1;
    cout << "Set 2: " << i2;
    i3=i1+i2;
    cout << "Union: " << i3;
    i3=i1^i2;
    cout << "Intersection: " << i3;
    i3=i1-i2;
    cout << "Difference (Set 1 - Set 2) " << i3;
    cout << "Add one interger to Set 1: ";
    cin >> addi;
    i3= i1+addi;
    cout << "Set 1: " << i3;
    Set<char>c1, c2, c3;
    char addc, rmc;
    cin >> c1;
    cin >> c2;
    cout << "Set 1: " << c1;
    cout << "Set 2: " << c2;
    c3=c1+c2;
    cout << "Union: " << c3;
    c3=c1^c2;
    cout << "Intersection: " << i3;
    c3=c1-c2;
    cout << "Difference (Set 1 - Set 2) " << c3;
    cout << "Add one interger to Set 1: ";
    cin >> addc;
    c3= c1+addc;
    cout << "Set 1: " << c3;
}
